name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm install
    - run: node_modules/.bin/semantic-release --dry-run -b ci2
    - run: echo "$(node_modules/.bin/semantic-release --dry-run -b ci2 | perl -ne '/(?<=The next release version is ).*(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*)))?(?:\-([\w][\w\.\-_]*))?)+/gi && print $&' | rev | cut -c1- | rev)"

    # - run: npm test
    # - run: npm run rollup
    # - run: npm run cli
    # - run: node_modules/.bin/semantic-release
    # - uses: actions/setup-node@v2-beta
    #   with:
    #     registry-url: 'https://npm.pkg.github.com'
    #     scope: '@snow-tree'
    # - run: node_modules/.bin/semantic-release
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}