name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm install
    - run: npm test
    - run: npm run rollup
    - run: npm run cli
    - run: node_modules/.bin/semantic-release
      if: github.ref != 'refs/heads/master'
