name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm install
    - run: npm test
    - run: npm run rollup
    - run: npm run cli 
    # - run: node_modules/.bin/semantic-release
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        MY_ENV_VAR: $(node_modules/.bin/semantic-release -b $(git branch --show-current) -d | perl -ne '/(?<=The next release version is ).*(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*)))?(?:\-([\w][\w\.\-_]*))?)+/gi && print $&' | rev | cut -c1- | rev)
    - name: Printenv
      run: |
        echo "MY_ENV_VAR=${MY_ENV_VAR}"
        printenv
    
    # - uses: actions/setup-node@v2-beta
    #   with:
    #     registry-url: 'https://npm.pkg.github.com'
    #     scope: '@snow-tree'
    # - run: npm version --no-git-tag-version $(node_modules/.bin/semantic-release -b $(git branch --show-current) -d | perl -ne '/(?<=The next release version is ).*(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*)))?(?:\-([\w][\w\.\-_]*))?)+/gi && print $&' | rev | cut -c1- | rev)
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #  if: github.ref == 'refs/heads/master'
    # - run: npm publish
    #   #  if: github.ref == 'refs/heads/master'
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}